### Last Edit Aug 5, 2018
###   - Changed toggle to toggle as required by Lovelace latest update 

title: My Home

excluded_entities:
  - weblink.router
views:
    # View tab title.
    - title: Main
      # Optional unique id for direct access /lovelace/${id}
      id: Main
#      theme: midnight
      # The cards to show on this view.
      cards:
        - type: vertical-stack
          cards:
            - type: entities
              title: LMS Player Controls
              entities:
                 - input_select.lms_player
                 - input_select.lms_source
                 - input_text.lms_artist
                 - input_text.lms_album
                 - input_text.lms_song
                 - input_text.lms_playlist
                 - input_select.lms_command
            - type: glance
              column_width: 33%
              show_state: false
              entities:
                 - entity: script.lms_cmd_pause_player
                   tap_action: toggle
                   name: Pause
                 - entity: script.lms_cmd_start_player
                   tap_action: toggle
                   name: Play
                 - entity: script.lms_cmd_next_track
                   tap_action: toggle
                   name: Next Track
            - type: glance
              column_width: 25%
              show_state: true
              entities:
                 - input_number.lms_volume
                 - input_number.lms_sleep_time
                 - entity: input_boolean.lms_shuffle
                   tap_action: toggle
                 - entity: input_boolean.lms_repeat
                   tap_action: toggle

        - type: entities
          title: LMS Sync Controls
          show_header_toggle: true
          entities:
            - input_select.lms_sync_master
            - input_boolean.lms_player1_sync
            - input_boolean.lms_player2_sync
            - input_boolean.lms_player3_sync
            - input_boolean.lms_player4_sync
            - input_boolean.lms_player5_sync
